#define ENGINE_DRIVE_LEFT_ENABLE 		68 		// P8_10
#define ENGINE_DRIVE_LEFT_DIRECTION 	44		// P8_12
#define ENGINE_DRIVE_LEFT_SPEED			23		// P8_13

#define ENGINE_DRIVE_RIGHT_ENABLE		3		// P9_21
#define ENGINE_DRIVE_RIGHT_DIRECTION	2		// P9_22
#define ENGINE_DRIVE_RIGHT_SPEED		40		// P9_40
